using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class LevelDevelopmentStageThree : LevelDevelopment
{
    public override IEnumerator RoutineLevel()
    {
        yield return new WaitForSeconds(3);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 3f), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 2f), Quaternion.identity);        
        yield return new WaitForSeconds(2);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(3);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(5);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 1), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 2), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 3), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 3.4f), Quaternion.identity);
        yield return new WaitForSeconds(5);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y + 3.4f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 3), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        yield return new WaitForSeconds(2);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        yield return new WaitForSeconds(3);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(4);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        yield return new WaitForSeconds(5);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y + 3.4f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 3), Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 1), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 3.4f), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 2), Quaternion.identity);
        yield return new WaitForSeconds(2);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 1), Quaternion.identity);
        yield return new WaitForSeconds(2);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 3.4f), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y + 2.4f), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 2), Quaternion.identity);
        yield return new WaitForSeconds(3);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y + 1.4f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 1), Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        yield return new WaitForSeconds(5);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(4);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        yield return new WaitForSeconds(3);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(4);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 2), Quaternion.identity);       
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 1.4f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 1.4f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 1), Quaternion.identity);
        yield return new WaitForSeconds(3);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 3), Quaternion.identity);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 2.4f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        yield return new WaitForSeconds(4);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 2), Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(3);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 1), Quaternion.identity);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 1), Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        yield return new WaitForSeconds(5);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 2.4f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 2), Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(6);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        yield return new WaitForSeconds(5);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(4);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        yield return new WaitForSeconds(3);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(4);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        yield return new WaitForSeconds(4);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 2.4f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 2), Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 2), Quaternion.identity);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y + 0.9f), Quaternion.identity);
        yield return new WaitForSeconds(4);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(3);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 2.4f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 2), Quaternion.identity);
        yield return new WaitForSeconds(4);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 1.4f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 2), Quaternion.identity);
        yield return new WaitForSeconds(4);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(3);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(2);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(5);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        yield return new WaitForSeconds(4);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        yield return new WaitForSeconds(4);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        yield return new WaitForSeconds(3);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        yield return new WaitForSeconds(3);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        yield return new WaitForSeconds(3);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", -transform.position, Quaternion.identity);
        yield return new WaitForSeconds(10);

        if (finish) StartCoroutine(Finish());
        yield return null;
    }

    public override void SaveScoreLost()
    {
        if (ScoreManager.ThreeScore <= ScoreManager.GetScore()) ScoreManager.ThreeScore = ScoreManager.GetScore();
        SaveData.SaveScore();
    }

    public override void SaveScoreAndUnlock()
    {
        if (ScoreManager.ThreeScore <= ScoreManager.GetScore()) ScoreManager.ThreeScore = ScoreManager.GetScore();       
        if (ScoreManager.GetUnlockedStage() == 2) ScoreManager.UnlockNewStage();
        if (!ScoreManager.unlockedAnim2)
        {
            ScoreManager.unlockedAnim2 = true;
            ScoreManager.AnimSelected = 2;
            AnimationOn = true;
        }
        SaveData.SaveScore();
    }
}
