using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class LevelDevelopmentStageSix : LevelDevelopment
{

    public override IEnumerator RoutineLevel()
    {
        yield return new WaitForSeconds(2);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y - 0.4f), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y + 0.4f), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 0.8f), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y + 1.2f), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 1.6f), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y + 2f), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 2.4f), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y + 2.8f), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 3.2f), Quaternion.identity);
        yield return new WaitForSeconds(4);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y - 0.4f), Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y), Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y + 0.4f), Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 0.8f), Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y + 1.2f), Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 1.6f), Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y + 2f), Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 2.4f), Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y + 2.8f), Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 3.2f), Quaternion.identity);
        yield return new WaitForSeconds(3);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y - 0.4f), Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y), Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y + 0.4f), Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 0.8f), Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y + 1.2f), Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 1.6f), Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y + 2f), Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 2.4f), Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y + 2.8f), Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 3.2f), Quaternion.identity);
        yield return new WaitForSeconds(5);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y - 0.4f), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 0.4f), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 0.8f), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 1.2f), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 1.6f), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 2), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 2.4f), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 2.8f), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 3.2f), Quaternion.identity);
        yield return new WaitForSeconds(4);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y - 0.4f), Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y), Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 0.4f), Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 0.8f), Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 1.2f), Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 1.6f), Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 2), Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 2.4f), Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 2.8f), Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 3.2f), Quaternion.identity);
        yield return new WaitForSeconds(3);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y - 0.4f), Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y), Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 0.4f), Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 0.8f), Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 1.2f), Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 1.6f), Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 2), Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 2.4f), Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 2.8f), Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 3.2f), Quaternion.identity);
        yield return new WaitForSeconds(5);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(4);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(3);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(5);
        ObjectsPool.UsePoolObject("Octagon", new Vector2(-transform.position.x, transform.position.y - 0.4f), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Octagon", new Vector2(transform.position.x, transform.position.y + 1.2f), Quaternion.identity);
        yield return new WaitForSeconds(1);
        ObjectsPool.UsePoolObject("Octagon", new Vector2(-transform.position.x, transform.position.y + 2.8f), Quaternion.identity);
        yield return new WaitForSeconds(4);
        ObjectsPool.UsePoolObject("Octagon", new Vector2(transform.position.x, transform.position.y - 0.4f), Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Octagon", new Vector2(-transform.position.x, transform.position.y + 1.2f), Quaternion.identity);
        yield return new WaitForSeconds(0.5f);
        ObjectsPool.UsePoolObject("Octagon", new Vector2(transform.position.x, transform.position.y + 2.8f), Quaternion.identity);
        yield return new WaitForSeconds(3);
        ObjectsPool.UsePoolObject("Octagon", new Vector2(-transform.position.x, transform.position.y - 0.4f), Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Octagon", new Vector2(transform.position.x, transform.position.y + 1.2f), Quaternion.identity);
        yield return new WaitForSeconds(0.25f);
        ObjectsPool.UsePoolObject("Octagon", new Vector2(-transform.position.x, transform.position.y + 2.8f), Quaternion.identity);
        yield return new WaitForSeconds(15);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y - 0.4f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y), Quaternion.identity);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y + 0.4f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 0.8f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y + 1.2f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 1.6f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y + 2f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 2.4f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(transform.position.x, transform.position.y + 2.8f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Triangle", new Vector2(-transform.position.x, transform.position.y + 3.2f), Quaternion.identity);
        yield return new WaitForSeconds(5);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y - 0.4f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y), Quaternion.identity);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 0.4f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 0.8f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 1.2f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 1.6f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 2), Quaternion.identity);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 2.4f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(-transform.position.x, transform.position.y + 2.8f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Diamond", new Vector2(transform.position.x, transform.position.y + 3.2f), Quaternion.identity);
        yield return new WaitForSeconds(5);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        ObjectsPool.UsePoolObject("Octahedron", transform.position, Quaternion.identity);
        yield return new WaitForSeconds(5);
        ObjectsPool.UsePoolObject("Octagon", new Vector2(-transform.position.x, transform.position.y - 0.4f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Octagon", new Vector2(transform.position.x, transform.position.y + 1.2f), Quaternion.identity);
        ObjectsPool.UsePoolObject("Octagon", new Vector2(-transform.position.x, transform.position.y + 2.8f), Quaternion.identity);
        yield return new WaitForSeconds(15);

        if (finish) StartCoroutine(Finish());

        yield return null;
    }

    public override void SaveScoreLost()
    {
        if (ScoreManager.SixScore <= ScoreManager.GetScore()) ScoreManager.SixScore = ScoreManager.GetScore();
        SaveData.SaveScore();
    }

    public override void SaveScoreAndUnlock()
    {
        if (ScoreManager.SixScore <= ScoreManager.GetScore()) ScoreManager.SixScore = ScoreManager.GetScore();     
        if (ScoreManager.GetUnlockedStage() == 5) ScoreManager.UnlockNewStage();
        if (!ScoreManager.unlockedAnim4)
        {
            ScoreManager.unlockedAnim4 = true;
            ScoreManager.AnimSelected = 4;
            AnimationOn = true;
        }
        SaveData.SaveScore();
    }
}
